Fix ATF build

diff --git a/generate_gxl_gxm_bootloader b/generate_gxl_gxm_bootloader
--- a/generate_gxl_gxm_bootloader
+++ b/generate_gxl_gxm_bootloader
@@ -102,16 +102,13 @@ echo "- Cleaning/Creating Amlogic U-Boot build directory..."
 cd ${TMPFS}
 make clean && make mrproper && make distclean
 
-# Only if official ATF firmware is not used
-if ! (( ATF_FW )); then
-  # Configure Amlogic U-Boot
-  echo "- Configure Amlogic U-Boot for ${BOARD} board..."
-  make ${BOARD}_defconfig
+# Configure Amlogic U-Boot
+echo "- Configure Amlogic U-Boot for ${BOARD} board..."
+make ${BOARD}_defconfig
 
-  # Compile Amlogic U-Boot
-  echo "- Compiling Amlogic U-Boot..."
-  make || error "Failed to compile Amlogic U-Boot!"
-fi
+# Compile Amlogic U-Boot
+echo "- Compiling Amlogic U-Boot..."
+make || error "Failed to compile Amlogic U-Boot!"
 
 # We need to go back into original directory
 cd ${OLDPWD}
